# Generated by Django 5.0.6 on 2024-07-23 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sevicio',
            new_name='Servicio',
        ),
    ]
