# Generated by Django 5.0.6 on 2024-09-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desarrollo',
            name='contenido',
            field=models.CharField(max_length=250),
        ),
    ]
