# Generated by Django 5.0.6 on 2024-09-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0002_alter_desarrollo_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desarrollo',
            name='contenido',
            field=models.CharField(max_length=150),
        ),
    ]
