# Generated by Django 5.1 on 2024-10-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestateapp", "0003_alter_desarrollo_contenido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="desarrollo",
            name="imagen",
            field=models.ImageField(upload_to="desarrollos/"),
        ),
    ]
