# Generated by Django 5.1 on 2024-08-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0002_producto_created_producto_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoriaprod",
            options={
                "verbose_name": "CategoriaProb",
                "verbose_name_plural": "CategoriasProb",
            },
        ),
    ]
